# Week 2: Text Cleaning & Normalization

This week focused on profiling and cleaning the MLS remarks column. The goal was to standardize common abbreviations, prices, measurements, unicode characters, HTML remnants, punctuation, and whitespace so the text is more consistent for future NLP tasks.

In [5]:
import sys
import os
import pandas as pd

sys.path.append(os.path.abspath(".."))

from scripts.text_cleaning import TextCleaner

df = pd.read_csv("../data/processed/listing_sample.csv")

cleaner = TextCleaner()

df.head()

,L_ListingID,L_Address,L_City,beds,baths,price,remarks
0,1190668831,1220 Johnson Drive 107,Ventura,2.0,2.0,650000,This is the special Gated 55+ Rancho Ventura h...
1,1174095292,850 Beech Street 511,San Diego,3.0,2.0,839900,"Experience uncompromised peace of mind, ultima..."
2,1190575810,141 Mellano Way,Oceanside,4.0,5.0,1299900,This two-story Next Gen® home that now include...
3,1189565343,2248 1/2 Gatewood Street,Los Angeles,2.0,3.0,665000,Thoughtful architecture meets iconic Eastside ...
4,1178725764,503 N Via Belmonte Court,Arroyo Grande,3.0,3.0,1999995,An extraordinary opportunity to own one of Arr...

In [6]:
print("Null count:", df["remarks"].isnull().sum())
print("Null rate:", df["remarks"].isnull().mean())
print("Average length:", df["remarks"].str.len().mean())
print("Median length:", df["remarks"].str.len().median())

Null count: 0
Null rate: 0.0
Average length: 1306.967
Median length: 1250.5

In [7]:
html_count = df["remarks"].str.contains(
    r"<[^>]+>",
    regex=True,
    na=False
).sum()

print("Rows with HTML:", html_count)

Rows with HTML: 0

In [8]:
price_count = df["remarks"].str.contains(
    r"\$\s*\d",
    regex=True,
    na=False
).sum()

print("Rows with price mentions:", price_count)

Rows with price mentions: 73

In [9]:
abbreviations = [
    "br", "bdr", "bdrm", "bd",
    "ba", "bath", "bth",
    "sqft", "sq ft", "sf",
    "w/", "w/o",
    "mbr", "mbdr",
    "lr", "dr", "fr",
    "kit", "gar",
    "ac", "a/c",
    "hw", "hdwd",
    "bsmt", "bsmnt",
    "apt", "condo",
    "pkg", "prkg",
    "lau", "lndry",
    "flr", "lvl",
    "yr", "yrs",
    "mo", "mins", "min",
    "approx", "incl", "excl"
]

In [10]:
import re

abbrev_counts = {}

for abbrev in abbreviations:
    pattern = r"(?<!\w)" + re.escape(abbrev) + r"(?!\w)"
    
    count = df["remarks"].str.count(
        pattern,
        flags=re.IGNORECASE
    ).sum()
    
    if count > 0:
        abbrev_counts[abbrev] = int(count)

abbrev_counts

{'br': 5,
 'bd': 3,
 'ba': 8,
 'bath': 536,
 'sqft': 34,
 'sq ft': 83,
 'sf': 37,
 'w/': 16,
 'dr': 10,
 'fr': 1,
 'ac': 32,
 'a/c': 59,
 'hw': 1,
 'condo': 139,
 'yrs': 1,
 'mins': 2,
 'min': 1,
 'approx': 20,
 'incl': 5}

## Data Profiling Findings

The remarks column contained no missing values and no HTML tags. The average remark length was about 1,307 characters, with a median length of about 1,251 characters. Price mentions appeared in 73 listings.

Several common real estate abbreviations were identified, including `bath`, `condo`, `sq ft`, `a/c`, `sf`, `sqft`, `ac`, `approx`, and `w/`. These findings helped determine which normalization rules were most relevant for the dataset.

In [12]:
bath_examples = df[
    df["remarks"].str.contains(
        r"\bbath\b",
        case=False,
        na=False
    )
]["remarks"].head(10)

for i, text in bath_examples.items():
    print(f"\nROW {i}:")
    print(text)
    print("-" * 80)

ROW 0:
This is the special Gated 55+ Rancho Ventura home you've been waiting for! Spacious and upgraded 1680sf of easy living on a large corner lot. Two generous bedrooms, plus a separate office/bonus room with a solar tube could be used for guests. There are two large sunny living spaces, and the family room has a lovely fireplace with a raised hearth.Tasteful upgrades include the granite kitchen with stainless appliances, the primary bath has been beautifully remodeled, all new windows, newer heating and central air-conditioning, lighting and ceiling fans, and gorgeous hardwood floors. Your outdoor space has a charming gazebo on the patio and a large side yard. Even the garage has new epoxy floors! The low $365 HOA fee includes water, sewer, trash, basic Spectrum cable/internet, and the use of all of Rancho Ventura's fabulous amenities: clubhouse, heated pool, spa, kitchen, library, weight room, billiards room, RV/Trailer parking and the friendliness neighbors in Ventura! Rancho Ventura is centrally located near the Victoria corridor, Kimball Park, shopping, restaurants, UCLA health and easy freeway access.
--------------------------------------------------------------------------------

ROW 3:
Thoughtful architecture meets iconic Eastside energy in one of Los Angeles' most creative and rapidly evolving neighborhoods. Be the first to live in this ground up new construction 2 bed, 2.5 bath residence. Make an immediate statement with its striking vertical slatted facade and custom green exterior. A design forward nod to Frogtown's creative spirit. Energy efficient solar panels keep your bills low and your footprint light. Inside, the aesthetic softens into a warm, organic palette layered with natural textures, clean lines, and abundant light.The open concept living space is airy and inviting, grounded by wide plank wood flooring and oversized windows that frame hillside views. The kitchen blends modern simplicity with warmth, featuring Euro white oak cabinetry, quartz countertops, stainless steel appliances, matte black fixtures, and thoughtfully placed windows that bring in natural light from multiple angles. The layout flows effortlessly from kitchen to dining to living, creating a space that feels both intimate and ideal for entertaining.Upstairs both bedrooms are en-suite retreats. Bathrooms are spa inspired and highly curated from the soft sage vertical tile surround with matte black fixtures to the terracotta tile shower paired with champagne hardware and glass enclosure. Each bath feels intentional, elevated, and design driven.A private patio and parking provide functional outdoor space, while the hillside backdrop and river-adjacent location place you moments from Frogtown's coffee shops, breweries, art studios, and the LA River bike path. This is modern Eastside living done right at a price that just makes sense.
--------------------------------------------------------------------------------

ROW 8:
Welcome to your detached single family dream home—spacious, stylish, and FULLY UPGRADED in Serrano Summit with NO MELLO-ROOS and LOW HOA! Offering the LARGEST FLOOR PLAN in the community and LUXURY TWO-STORY LIVING with a bonus room and partially covered outdoor balcony on the third floor. Built in 2021 and offering over 3,400 sq ft of thoughtfully designed living space, this home blends contemporary design with everyday comfort and includes a FULLY PAID SOLAR SYSTEM for added savings.
The spacious & functional layout centers around a huge kitchen and family great room, ideal for both daily living & entertaining. Upon entry, you’re greeted by a striking stacked stone feature wall, white oak wood flooring, and designer lighting that immediately set a refined tone. The chef’s kitchen shines with high-end GE Café appliances, massive quartz island, custom pantry, wine cooler, soft-close drawer systems, a whole-house water filtration system with reverse osmosis, and a refrigerator with a built-in hot water dispenser. A first-floor in-law bedroom with ensuite bath and walk-in closet provides the perfect solution for guests or multigenerational living.
Upstairs, the primary suite is a true retreat featuring motorized blackout shades, a designer barn door, and a spa-like bathroom complete with dual sinks, a separate custom vanity with a heated and lighted mirror, and a reverse osmosis water system, and a fully customized walk-in closet. A versatile second-floor loft adds flexible living space—ideal for a home office, study area, or playroom. The third-floor bonus room includes a walled-off area with a large window, creating a fully enclosed space that contains noise from TV and conversations and keeps out heat from below, and has its own dedicated heating and cooling system.
Outdoor living is seamless with tiled flooring that extends from the interior, a built-in fire pit with custom seating, raised garden beds, mature fruit trees, bistro lighting, and a convenient exterior sink designed for gardening and clean-up. Additional highlights include a finished garage with epoxy floors, Tesla charger, smart home features, luxury carpet, fire sprinkler system, and mountain-view balcony space ideal for relaxing or gathering.
Enjoy exclusive access to Serrano Summit’s Summit Club, featuring a resort-style pool with beach entry, heated spa, cabanas, BBQ areas, and pickleball courts. Thoughtfully designed, meticulously upgraded, and truly special—this home stands apart.
--------------------------------------------------------------------------------

ROW 10:
Meet this Historic Grandeur with Modern Flexibility in the Heart of Fresno, 1407 E Princeton Ave, Fresno, Step into a timeless piece of Fresno history with this stunning 1920s two-story, 2976 square foot estate ideally located between Fresno City College and the beloved Christmas Tree Lane. From the moment you arrive, the gated circular driveway and iconic California palms create a striking first impression. Elegant Living with Flexible Possibilities new LVP flooring installed, Offering 3 bedrooms with new carpet in each room and 3 bathrooms, this home blends classic architecture with modern-day versatility, Private ADU Opportunity Just off the front entry, a grand formal parlor with glass French doors and a fireplace is currently configured as a private living space, ideal for guests, multigenerational living, or potential rental income, with convenient access to a nearby full bath. Light-Filled Interiors Expansive windows bathe the home in natural light, while a west-facing slider creates effortless indoor-outdoor flow. Designed for Entertaining, The spacious living room, formal dining area with fireplace and a well-appointed kitchen provide a warm and inviting setting for gatherings.
Exceptional Storage & Bonus Spaces Includes a dedicated laundry area, pantry with custom built-ins, sunroom/lanai, and a full basement rare for homes of this era. Upstairs Retreats
Primary Suite Escape: Features an original fireplace, access to a sun porch with a jetted tub, and
a beautifully updated shared bath with dual-head shower. Secondary Suite: A generously sized bedroom with its own private bathroom and balcony overlooking the front grounds. Third Suite: A spacious multipurpose room with dual closets and a sitting room. Thoughtful upgrades include, Owned Solar System Enjoy energy efficiency and long-term savings. Major Updates Completed:
Including roof, water heater, windows, and HVAC system Resort-Style Backyard: Relax or entertain in your private oasis with a pool, water fall feature, and slate stone patio. Expanded Utility Space Additional graveled parking with power and sewer hookups perfect for RVs, trailers, electric car charging, or future expansion Future ADU Potential the Seller-submitted plans to the City of Fresno for an additional unit. Enhanced security equipped with a comprehensive camera system. This home Offers a charming, historic ambiance and is conveniently located near Lafayette Park, making it ideal for walkers, cyclists, and pet owners.
--------------------------------------------------------------------------------

ROW 11:
Rare, highly sought after NE Corner live/work industrial loft at the coveted Biscuit Company Lofts. Open and spacious floor plan, 15' ceilings, oversized industrial windows with breathtaking views of the Downtown city lights. New Bosch oven/range cooktop, microwave and appliances. Large En-suite master bath and guest bathroom available. MILLS ACT APPROVED saving owner up to 70-75% off property taxes. New paint (including ceilings).  New Washer and dryer included. Amenities include 24 hour front desk/doorman, gated/secured parking, 75' lap pool, gym and an outdoor BBQ station. Wireless and Scalable Internet & Telecomm. 1 deeded parking space in secured subterranean garage with *BONUS* EV charger, pets ok.  The subject property is ideally located within short distance to local favorites like Hauser & Wirth Gallery, Moto Shed, Hanks (Gourmet Market), Camelia, Flamingo Bar, upcoming Silverlake Wine Bar, Bavel, Manuela, Factory Kitchen, Girl & The Goat, Zinc Cafe, Bestia, Damian, Verve Coffee Roasters, Death & Co, Soho House, and a host of other entertainment and dining venues. HOA dues cover Water, trash, & gas. Residents pay electricity & Internet separately.
--------------------------------------------------------------------------------

ROW 15:
Welcome to 207 Ocean Ave Extension - a Rare Coastal Legacy Property with Panoramic Ocean Views. Available for the first time in over half a century, this 2-bedroom, 2-bath approx. 2130 sqf residence offers expansive views over Rustic Canyon to the Pacific Ocean, Malibu coastline, and Santa Monica Mountains from multiple rooms. The residence reflects classic Coastal Craftsman cottage architecture with period detailing and a modest footprint. The multi-level grounds may be reimagined to create terraced gardens, additional outdoor living spaces, and enhanced entertaining areas, subject to buyer investigation and applicable governmental approvals. The expansive outdoor areas provides a peaceful retreat, ideal for morning coffee, quiet afternoons, or alfresco evenings under the stars. The unfinished attic area | storage area (included in total sqf of the home ~ 665sqf) offers potential for conversion into additional living space, subject to buyer verification. A one car garage is attached (convenient street parking is available) and an additional spacious storage area is located beneath the house. Positioned along the Ocean Avenue Extension corridor, the property is approximately one block from Palisades Park and near the beach and Montana Avenue. This established coastal neighborhood offers convenient access to dining, shopping, and everyday amenities. Residents enjoy a blend of coastal nature and walkability. Nearby destinations include the historic Golden Bull Steakhouse, Giorgio Baldi, Muse, La Monique, Fig, Wally's, Hillstone restaurants, local coffee shops, grocers such as Whole Foods and Ralphs, along with a rotating local gallery on Channel Road and art galleries along Montana and Ocean Avenues. The area is also home to Canyon Elementary School and the Canyon Recreation Center, which offers tennis courts, sports fields, and community events throughout the year. Additional nearby amenities include the Annenberg Community Beach House, scenic pedestrian paths, and coastal stairways frequently used for outdoor recreation and neighborhood gatherings. Whether restored, reimagined, or thoughtfully expanded, the property offers exceptional potential in a location with consistent buyer interest. Ocean-view properties in this area continue to attract attention, supported by limited available inventory and proximity to nearby coastal amenities. The mailing address is Santa Monica; however, the property is located within the City of Los Angeles and subject to Los Angeles services and regulations. Sold as a fixer-upper, offering an opportunity to renovate, enhance, and reimagine the existing home while preserving its unique character. The adjacent vacant parcel is not included in the offering and is not currently available for purchase. Some photos are virtually staged or digitally enhanced. Original photos are included.
--------------------------------------------------------------------------------

ROW 16:
Located in the highly desirable Westridge neighborhood, this impressive 2.62+/- acre property offers views, room for expansion, a vineyard, a separate ADU, and a freshly updated home with 4 bedrooms and 3 remodeled baths. The kitchen has new appliances and flows into a family living space. The large dining area sets the stage for entertaining. The Primary Suite has a tall, beamed ceiling, 3 closets and a deck that overlooks the property and Windy Hill views. Additional bedrooms enjoy a private wing that centers around a flexible space. This space is served by a separate entrance for flexibility. A lower level is a blank slate. It has a workshop, lots of storage, 2 rooms with sliding glass doors, a large well-lit space thats ideal as a game room or exercise center and a full bath. Potential for a wine cellar. The ADU is 1 bed, 1 bath and has an open living/dining/kitchenette space, as well as a private deck and entrance. There is a small upper pasture and a large area at the front of the property that could be used for horses, a pool, or possibly a tennis court. Central Portola Valley location, convenient to shopping, Alpine Hills Tennis and Swim Club, The Alpine Inn, excellent PV schools and easy commute routes.
--------------------------------------------------------------------------------

ROW 19:
Turnkey and fully furnished, this one-bedroom, one-bathroom retreat sits on the second floor of the G building at North Coast Village, the oceanfront resort community set between the Oceanside Pier and the Harbor. A private covered balcony captures views of swaying palms and the community's lush, tropical grounds.

The interior offers a seamless open layout, connecting the breakfast-bar kitchen and dining area to a living room anchored by a tile-surround fireplace. Ceiling fans keep the air moving throughout, while the bedroom features generous mirrored closets. The full bath offers both a tub and shower, and the home is move-in ready.

Life here feels like a permanent vacation with direct beach access and an impressive array of amenities. Spend your afternoons lounging by one of the two heated pools and spas, practicing on the putting green, or wandering past serene koi ponds and waterfalls. The community also features a fitness center with saunas, billiards and game rooms, a recreation room, and dedicated barbecue areas. Convenience is built in with garage parking and 24-hour gated security.

Whether you're looking for a coastal getaway, a second home, or a full-time residence by the water, you're just moments from the Thursday Sunset Market, the harbor's waterfront dining, and the eclectic shops of downtown Oceanside. With the beach strand and bike path right across the street, the best of the coast is at your doorstep.
--------------------------------------------------------------------------------

ROW 20:
CHARMING SINGLE-STORY IN SUMMERLY — Welcome to this beautifully maintained 2018-built home with 2,796 sq ft on a 7,405 sq ft lot in one of Lake Elsinore's premier master-planned communities. This 3-bedroom, 2.5-bath layout stands out. The open-concept kitchen impresses with espresso cabinetry, a large island with waterfall-style counters, mosaic tile backsplash, stainless steel appliances, and modern pendant lighting. It flows seamlessly into the adjacent great room, anchored by a stacked-stone fireplace with a mounted TV niche — perfect for everyday living and entertaining.
Wood-look plank tile flooring runs throughout the home, paired with soft neutral paint and crisp white trim. The generously sized bedrooms and walk-in closet offer abundant storage, while the bathroom features a rich dark wood vanity with counters and a tub/shower combo. A dedicated laundry room with built-in overhead shelving adds everyday convenience. Outside, the home makes a great first impression with a tile roof, arched entry, and drought-tolerant landscaping accented by mature trees and decorative rock. The attached 3-car tandem garage and low-maintenance yard complete this move-in-ready home. Summerly residents enjoy community parks, a splash pad, walking trails, and year-round events, just minutes from shopping, dining, and easy freeway access.
--------------------------------------------------------------------------------

ROW 21:
Million Dollar, Panoramic Mountain Views overlooking three local wineries and Palomar Mountain. This property is a rare find situated on owned land with no lease fee. The home is located on the western edge of the community providing unobstructed views and unforgettable sunsets from your large private deck that feels like your own mountain chalet.  This 2-bed, 2-bath home offers 1,344 square feet and is beautifully maintained and completely updated with stainless steel appliances, newer cabinetry, elegant quartz counter tops, luxury vinyl plank flooring, free-standing soaking tub, and dual-pane windows to enhance both style and energy efficiency. The inviting living area is anchored by a cozy wood-burning fireplace with insert, creating the perfect setting for cool mountain evenings. Step outside to enjoy the private side yard entrance, complete with garden, fully enclosed vinyl fencing & gate for added privacy. Additional highlights include a newer roof and numerous modern updates that make this home truly move-in ready. Located in the 55+ community of Stone Ridge, residents enjoy an active social calendar with scheduled Clubhouse activities, along with fishing and hiking opportunities.  Centrally located near Julian, Ramona, and Borrego Springs, scenic countryside drives and exploration await.  Just 30 miles from Temecula for major shopping, dining, and medical services.  If you are looking for peaceful living, vibrant sunsets, vineyard and mountain views, and a beautifully updated home in a welcoming community...this Stone Ridge gem is not to be missed!
--------------------------------------------------------------------------------

In [13]:
cleaner = TextCleaner()

cleaner.expand_abbreviations("3 br 2 ba home w/ ac")

'3 bedroom 2 bathroom home with air conditioning'

In [14]:
cleaner.normalize_prices("priced at 450k")

'priced at 450000'

In [15]:
cleaner.normalize_prices("$1.2m home")

'$1200000 home'

In [16]:
cleaner.normalize_prices("Listed at 750K")

'Listed at 750000'

In [17]:
profile = cleaner.profile_column(df, "remarks")

profile

{'null_rate': 0.0,
 'null_count': 0,
 'avg_length': 1306.967,
 'median_length': 1250.5,
 'price_mentions': 73,
 'has_html': 0,
 'unicode_issues': 355,
 'common_terms': [('and', 9358),
  ('the', 8582),
  ('a', 7858),
  ('with', 3623),
  ('to', 3358),
  ('of', 2896),
  ('in', 2881),
  ('for', 2540),
  ('home', 2461),
  ('this', 2218),
  ('living', 1853),
  ('is', 1752),
  ('an', 1639),
  ('room', 1318),
  ('space', 1153)],
 'common_abbreviations': [('bath', 536),
  ('condo', 139),
  ('sq ft', 83),
  ('a/c', 60),
  ('w/', 49),
  ('sf', 37),
  ('sqft', 34),
  ('ac', 32),
  ('approx', 20),
  ('dr', 10),
  ('ba', 8),
  ('br', 5),
  ('incl', 5),
  ('bd', 3),
  ('rec', 2),
  ('mins', 2),
  ('yrs', 1),
  ('fr', 1),
  ('min', 1),
  ('hw', 1)]}

### Abbreviation Validation

Some terms were checked manually before being added to the normalization rules because they could be ambiguous. For example, listings containing the word `bath` were reviewed to confirm that it was being used to refer to a bathroom in this dataset.

In [18]:
terms_df = pd.DataFrame(
    profile["common_terms"],
    columns=["term", "count"]
)

terms_df

      term  count
0      and   9358
1      the   8582
2        a   7858
3     with   3623
4       to   3358
5       of   2896
6       in   2881
7      for   2540
8     home   2461
9     this   2218
10  living   1853
11      is   1752
12      an   1639
13    room   1318
14   space   1153

In [19]:
abbrev_df = pd.DataFrame(
    profile["common_abbreviations"],
    columns=["abbreviation", "count"]
)

abbrev_df.head(20)

   abbreviation  count
0          bath    536
1         condo    139
2         sq ft     83
3           a/c     60
4            w/     49
5            sf     37
6          sqft     34
7            ac     32
8        approx     20
9            dr     10
10           ba      8
11           br      5
12         incl      5
13           bd      3
14          rec      2
15         mins      2
16          yrs      1
17           fr      1
18          min      1
19           hw      1

## Text Cleaning Pipeline

The `TextCleaner` class applies several normalization steps:

- Unicode normalization
- HTML removal
- Price normalization
- Measurement normalization
- Abbreviation expansion
- Punctuation normalization
- Whitespace normalization

The complete pipeline is applied to each MLS remark to create a new `remarks_clean` column while preserving the original remarks for comparison.

In [20]:
df["remarks_clean"] = df["remarks"].apply(cleaner.clean_text)

df.head()

,L_ListingID,L_Address,L_City,beds,baths,price,remarks,remarks_clean
0,1190668831,1220 Johnson Drive 107,Ventura,2.0,2.0,650000,This is the special Gated 55+ Rancho Ventura h...,This is the special Gated 55+ Rancho Ventura h...
1,1174095292,850 Beech Street 511,San Diego,3.0,2.0,839900,"Experience uncompromised peace of mind, ultima...","Experience uncompromised peace of mind, ultima..."
2,1190575810,141 Mellano Way,Oceanside,4.0,5.0,1299900,This two-story Next Gen® home that now include...,This two-story Next Gen® home that now include...
3,1189565343,2248 1/2 Gatewood Street,Los Angeles,2.0,3.0,665000,Thoughtful architecture meets iconic Eastside ...,Thoughtful architecture meets iconic Eastside ...
4,1178725764,503 N Via Belmonte Court,Arroyo Grande,3.0,3.0,1999995,An extraordinary opportunity to own one of Arr...,An extraordinary opportunity to own one of Arr...

In [22]:
df.to_csv(
    "../data/processed/week2_cleaned.csv",
    index=False
)

In [23]:
changed = df[
    df["remarks"] != df["remarks_clean"]
][["remarks", "remarks_clean"]]

changed.head(10)

,remarks,remarks_clean
0,This is the special Gated 55+ Rancho Ventura h...,This is the special Gated 55+ Rancho Ventura h...
1,"Experience uncompromised peace of mind, ultima...","Experience uncompromised peace of mind, ultima..."
2,This two-story Next Gen® home that now include...,This two-story Next Gen® home that now include...
3,Thoughtful architecture meets iconic Eastside ...,Thoughtful architecture meets iconic Eastside ...
5,Location! Location! Great Location! This char...,Location! Location! Great Location! This charm...
6,"This beautiful one bedroom, one bathroom home ...","This beautiful one bedroom, one bathroom home ..."
7,Modern Living with Room to Breathe.\r\r\nEscap...,Modern Living with Room to Breathe. Escape to ...
8,Welcome to your detached single family dream h...,Welcome to your detached single family dream h...
10,Meet this Historic Grandeur with Modern Flexib...,Meet this Historic Grandeur with Modern Flexib...
11,"Rare, highly sought after NE Corner live/work ...","Rare, highly sought after NE Corner live/work ..."

In [24]:
pd.set_option("display.max_colwidth", 200)

changed.head(5)

,remarks,remarks_clean
0,"This is the special Gated 55+ Rancho Ventura home you've been waiting for! Spacious and upgraded 1680sf of easy living on a large corner lot. Two generous bedrooms, plus a separate office/bonus ro...","This is the special Gated 55+ Rancho Ventura home you've been waiting for! Spacious and upgraded 1680 square feet of easy living on a large corner lot. Two generous bedrooms, plus a separate offic..."
1,"Experience uncompromised peace of mind, ultimate privacy, and resort-style living at The Discovery in Cortez Hill. High-rise living in downtown San Diego is at its absolute finest when backed by a...","Experience uncompromised peace of mind, ultimate privacy, and resort-style living at The Discovery in Cortez Hill. High-rise living in downtown San Diego is at its absolute finest when backed by a..."
2,"This two-story Next Gen® home that now includes backsplashes and upgraded flooring and is ready for a Quick Move-In, features a private suite with a separate entrance, living area, kitchenette and...","This two-story Next Gen® home that now includes backsplashes and upgraded flooring and is ready for a Quick Move-In, features a private suite with a separate entrance, living area, kitchenette and..."
3,"Thoughtful architecture meets iconic Eastside energy in one of Los Angeles' most creative and rapidly evolving neighborhoods. Be the first to live in this ground up new construction 2 bed, 2.5 bat...","Thoughtful architecture meets iconic Eastside energy in one of Los Angeles' most creative and rapidly evolving neighborhoods. Be the first to live in this ground up new construction 2 bed, 2.5 bat..."
5,"Location! Location! Great Location! This charming Greek-inspired, blue-and-white ranch-style home is tucked away on a peaceful, sought-after cul-de-sac in the heart of Midtown Palo Alto. The home...","Location! Location! Great Location! This charming Greek-inspired, blue-and-white ranch-style home is tucked away on a peaceful, sought-after cul-de-sac in the heart of Midtown Palo Alto. The home ..."

In [25]:
changed_count = (
    df["remarks"] != df["remarks_clean"]
).sum()

changed_rate = changed_count / len(df)

print(f"Remarks changed: {changed_count:,}")
print(f"Percentage changed: {changed_rate:.2%}")

Remarks changed: 863
Percentage changed: 86.30%

In [26]:
df["original_length"] = df["remarks"].str.len()

df["clean_length"] = df["remarks_clean"].str.len()

print(
    "Average original length:",
    df["original_length"].mean()
)

print(
    "Average cleaned length:",
    df["clean_length"].mean()
)

Average original length: 1306.967
Average cleaned length: 1308.25

## Results

The cleaned remarks were compared with the original remarks to determine how frequently the pipeline changed the text. Before-and-after examples were also reviewed to make sure the normalization rules improved consistency without changing the intended meaning.

The cleaned dataset was saved as `data/processed/week2_cleaned.csv` for use in later stages of the project.